# Generated by Django 5.2.10 on 2026-01-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        choices=[
                            ("greeting", "인삿말"),
                            ("profile", "프로필"),
                            ("awards", "수상내역"),
                            ("curriculum", "커리큘럼"),
                            ("accompanist", "반주자 매칭"),
                            ("soloist", "솔리스트 매칭"),
                            ("masterclass", "마스터 클래스"),
                        ],
                        help_text="페이지 고유 키입니다. 신규 생성 시에만 설정하세요.",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="pages/hero/"),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="pages/files/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
    ]
