# Generated by Django 5.2.10 on 2026-01-14 10:24

from django.db import migrations


def seed_pagecontent(apps, schema_editor):
    page_content = apps.get_model("pages", "PageContent")
    defaults = [
        ("greeting", "인삿말"),
        ("profile", "프로필"),
        ("awards", "수상내역"),
        ("curriculum", "커리큘럼"),
        ("accompanist", "반주자 매칭"),
        ("soloist", "솔리스트 매칭"),
        ("masterclass", "마스터 클래스"),
    ]

    for key, title in defaults:
        page_content.objects.get_or_create(key=key, defaults={"title": title})


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_pagecontent, migrations.RunPython.noop),
    ]
