# Generated by Django 5.2.10 on 2026-01-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitebrandsettings",
            old_name="masthead_hero_image",
            new_name="masthead_banner_image",
        ),
        migrations.AlterField(
            model_name="sitebrandsettings",
            name="masthead_banner_image",
            field=models.ImageField(
                blank=True,
                help_text="홈 상단 배너 배경에 사용되는 이미지입니다.",
                null=True,
                upload_to="brand/",
                verbose_name="메인 배너 이미지",
            ),
        ),
    ]
