# Generated by Django 5.2.10 on 2026-01-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0003_rename_masthead_banner_image_to_main_banner_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBannerSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="brand/banners/")),
                ("title", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "홈 배너 슬라이드",
                "verbose_name_plural": "홈 배너(슬라이드)",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
