# Generated by Django 5.2.10 on 2026-01-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0005_awardcertificate_roadmapimagecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebrandsettings',
            name='hero_mini_image_1',
            field=models.ImageField(blank=True, help_text='홈 우측 미니 이미지(정사각형). 권장: 600x600', null=True, upload_to='brand/hero/', verbose_name='홈 미니 이미지 1'),
        ),
        migrations.AddField(
            model_name='sitebrandsettings',
            name='hero_mini_image_2',
            field=models.ImageField(blank=True, help_text='홈 우측 미니 이미지(정사각형). 권장: 600x600', null=True, upload_to='brand/hero/', verbose_name='홈 미니 이미지 2'),
        ),
        migrations.AddField(
            model_name='sitebrandsettings',
            name='hero_wide_image',
            field=models.ImageField(blank=True, help_text='홈 좌측 하단 가로 이미지. 권장: 1600x280', null=True, upload_to='brand/hero/', verbose_name='홈 가로 이미지'),
        ),
        migrations.AlterField(
            model_name='awardcertificate',
            name='image',
            field=models.ImageField(help_text='수상 경력 이미지. 권장: 900x1200', upload_to='brand/awards/'),
        ),
        migrations.AlterField(
            model_name='homebannerslide',
            name='image',
            field=models.ImageField(help_text='홈 상단 슬라이드 이미지. 권장: 1600x900', upload_to='brand/banners/'),
        ),
        migrations.AlterField(
            model_name='roadmapimagecard',
            name='image',
            field=models.ImageField(help_text='로드맵 이미지 카드. 권장: 900x600', upload_to='brand/roadmap/'),
        ),
        migrations.AlterField(
            model_name='sitebrandsettings',
            name='main_banner_image',
            field=models.ImageField(blank=True, help_text='홈 상단 메인 배너에 사용되는 이미지입니다. 권장: 1600x900', null=True, upload_to='brand/', verbose_name='메인 배너 이미지'),
        ),
    ]
